# roles/collectd/tasks/server.yml
# Tasks specific for the collectd server
---

- name: Ensure data directory exists
  file:
    path: "/var/lib/collectd/rrd"
    state: directory
  tags: collectd

- name: Install rrdtool configuration file
  template:
    src: etc_collectd_d_rrdtool.conf.j2
    dest: "/etc/collectd.d/rrdtool.conf"
    validate: "collectd -t -C %s"
  notify: restart collectd
  tags: collectd

