# roles/collectd/tasks/web.yml
# Installation of collectd-web, which should only happen when
# `collectd_web_enabled` is true and this host is the server
---

- name: Install packages for collectd-web
  yum:
    pkg: "collectd-web"
    state: installed
  tags: collectd

- name: Ensure web server is started
  service:
    name: "httpd"
    state: started
    enabled: true
  tags: collectd

- name: Install Apache configuration file
  template:
    src: etc_httpd_conf.d_collectd.conf.j2
    dest: "/etc/httpd/conf.d/collectd.conf"
  notify: restart httpd
  tags: collectd

