# host_vars/lampstacknginx.yml
---
el7_repositories:
  - epel-release
el7_install_packages:
  - bash-completion
  - policycoreutils
  - setroubleshoot-server
  - tree
  - vim-enhanced
el7_firewall_allow_services:
  - http
  - https
  - mysql
el7_firewall_allow_ports:
  - 25826/udp
  - 3306/tcp
mariadb_databases:
  - wordpress
mariadb_users:
  - name: user
    password: WopWop
    priv: 'wordpress.*:ALL'
mariadb_root_password: WopWop
mariadb_init_scripts:
  - database: wordpress
    script: init.sql
httpd_scripting: 'php'