# host_vars/lampstack.yml
---

el7_repositories:
  - epel-release

el7_install_packages:
  - bash-completion
  - policycoreutils
  - setroubleshoot-server
  - tree
  - vim-enhanced

el7_firewall_allow_services:
  - http
  - https

httpd_scripting: 'php'

mariadb_databases:
  - wordpress

mariadb_users:
  - name: user
    password: WopWop
    priv: 'wordpress.*:ALL'

mariadb_root_password: WopWop

wordpress_database: wordpress
wordpress_user: user
wordpress_password: WopWop
wordpress_plugins: 
  - name: demo-data-creator
    version: ''
# mariadb_init_scripts:
  # - database: wordpress
    # script: init.sql

collectd_plugins:
  plugin: "load"
  plugin: "memory"
  
collectd_plugins_multi:
  interface: {Interface: "eth0"}
  disk: {Disk: "sda"}
  network: {Server: "192.168.56.10"}
  