# site.yml
---
- hosts: lampstack
  sudo: true
  roles:
    - bertvv.el7
    - sepolicy
    - bertvv.httpd
    - bertvv.mariadb
    - bertvv.wordpress
    - phpmyadmin
    - collectd

- hosts: collectdsrv
  sudo: true
  roles:
    - bertvv.el7
    - collectd
    - graphite