# site.yml
---
- hosts: lampstack
  sudo: true
  roles:
    - bertvv.el7
    - sepolicy
    - bertvv.httpd
    - bertvv.mariadb
    - bertvv.wordpress
    - phpmyadmin
    - bertvv.collectd

- hosts: monisrv
  sudo: true
  roles:
    - bertvv.el7
    - bertvv.collectd